from . import leak_1_sql_injection
from . import leak_2_unsafe_sudo
from . import leak_3_master_the_rules
from . import leak_4_guard_password_and_tokens_fiercely
from . import leak_5_sea_surf
from . import leak_6_xss
from . import leak_7_open_with_care
from . import leak_8_eval_is_evil
from . import leak_9_dangerous_objects
from . import leak_10_unsafe_getattr_setattr
from . import leak_11_you_shall_not_pickle
