from . import account_move
from . import account_move_line
from . import blacklist
from . import compose_message
from . import hr_payslip
from . import mail_channel
from . import mail_channel_partner
from . import payment_acquirer
from . import project
from . import sign_template
from . import task
