from . import common
from . import test_leak_1_sql_injection
from . import test_leak_2_unsafe_sudo
from . import test_leak_3_master_the_rules
from . import test_leak_4_guard_password_and_tokens_fiercely
from . import test_leak_5_sea_surf
from . import test_leak_6_xss
from . import test_leak_7_open_with_care
from . import test_leak_8_eval_is_evil
from . import test_leak_9_dangerous_objects
from . import test_leak_10_unsafe_getattr_setattr
from . import test_leak_11_you_shall_not_pickle
